<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="DTOS\**" />
    <EmbeddedResource Remove="DTOS\**" />
    <None Remove="DTOS\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\TaskDomain.csproj" />
  </ItemGroup>

</Project>
