<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\Persistance\Persistance.csproj" />
    <ProjectReference Include="..\Modules\Debt\DebtInfrastructure\DebtInfrastructure.csproj" />
    <ProjectReference Include="..\Modules\Finance\Infrastructure\FinanceInfrastructure.csproj" />
    <ProjectReference Include="..\Modules\StorePlant\PlantInfrastructure\PlantInfrastructure.csproj" />
    <ProjectReference Include="..\Modules\TaskManagement\TaskInfrastructure\TaskInfrastructure.csproj" />
    <ProjectReference Include="..\Modules\TimeTracking\Infrastructure\TimeTrackingInfrastructure.csproj" />
    <ProjectReference Include="..\Modules\UserIdentity\Infrastructure\UserIdentityInfrastructure.csproj" />
    <ProjectReference Include="..\Persentation\Persentation.csproj" />
  </ItemGroup>

</Project>
